"use client";
import type { Metadata } from "next";

import "./globals.css";
import { customTheme, darkTheme, lightTheme } from "@/themes/custom-theme";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { Navbar } from "../components/Navbar";
import axios from "axios";
import { useState, useEffect } from "react";

// export const metadata: Metadata = {
//   title: "Cookie Master",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [theme, setTheme] = useState<"dark" | "light" | "custom">("light");

  useEffect(() => {
    const getTheme = async () => {
      const { data } = await axios.get("/api/theme");
      setTheme(data.theme);
    };
    getTheme();
  }, []);

  const returnTheme = () => {
    const themes = {
      dark: darkTheme,
      light: lightTheme,
      custom: customTheme,
    };

    return themes[theme];

    // if (theme === "dark") {
    //   return darkTheme;
    // } else if (theme === "light") {
    //   return lightTheme;
    // } else {
    //   return customTheme;
    // }
  };

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap"
        />
      </head>
      <ThemeProvider theme={returnTheme()}>
        <CssBaseline />
        <body>
          <Navbar></Navbar>
          <main style={{ padding: "30px" }}>{children}</main>
        </body>
      </ThemeProvider>
    </html>
  );
}
